import type { DomainPack } from './types'

export const aviationPack: DomainPack = {
  id: 'aviation',
  label: '항공서비스',
  matchKeywords: ['항공', '승무원', '객실', '공항', '기내', '항공서비스'],
  courseNatureTemplate:
    '고객 응대와 안전 절차가 동시에 요구되는 실무 중심 과목으로, 표준화된 서비스 매뉴얼 준수와 상황별 유연한 대응력을 함께 길러야 한다. 안전 관련 내용은 절차 오류가 곧 사고로 이어질 수 있어 엄격한 기준으로 평가한다.',
  studentCharacteristics:
    '실제 승객 응대 상황을 가정한 역할극·시뮬레이션에서 학습 동기가 높으며, 표준 매뉴얼 암기보다 실전 대응 능력을 더 중요하게 인식하는 경향이 있다.',
  prerequisitesPool: [
    '서비스 산업 기초 개념',
    '기초 영어 커뮤니케이션 능력',
    '항공 산업 개관에 대한 이해',
    '이미지 메이킹 및 기본 매너 소양',
  ],
  coreConcepts: [
    '고객 응대(그루밍, 매너, 표준 화법)',
    '서비스 회복(Service Recovery)',
    '기내 안전 절차 및 비상 대응',
    '고객경험(CX) 설계',
    '문화적 다양성 응대',
    '컴플레인 처리 프로세스',
    '팀워크 및 승무원 간 협업(CRM)',
    '항공 서비스 트렌드',
  ],
  difficultiesPool: [
    '표준 매뉴얼과 실제 돌발 상황 대응 사이의 간극을 좁히기 어려움',
    '감정노동 상황에서 서비스 표준을 유지하는 훈련이 부족',
    '안전 절차와 서비스 응대를 동시에 수행하는 멀티태스킹 훈련 필요',
    '다양한 국적·문화의 승객 응대 경험 부족',
  ],
  aiApplicability:
    'AI는 고객 응대 시나리오 초안, 컴플레인 대응 스크립트, 표준 화법 예시 생성에 유용하다. 다만 실제 비상 안전 절차와 규정은 항공사·항공안전 지침을 우선하며 AI 결과는 참고용 초안으로만 활용한다.',
  instructorJudgmentPool: [
    'AI가 생성한 응대 스크립트가 실제 항공사 서비스 규정과 일치하는지 검토',
    '안전 절차 관련 내용은 최신 항공안전 지침으로 교차 확인',
    '문화적 다양성 시나리오의 적절성 최종 판단',
  ],
  weekTopics: [
    {
      title: '항공 서비스 산업의 이해',
      coreConcepts: '항공 산업 구조, 승무원의 역할, 서비스 산업 특성',
      teachingHint: '항공 서비스 산업 개관 강의',
      studentHint: '항공사별 서비스 사례 조사 및 발표',
      practiceHint: '항공사 서비스 비교 분석 실습',
      aiUsageHint: 'AI로 항공사별 서비스 특징 비교표 초안 생성',
    },
    {
      title: '이미지 메이킹과 기본 매너',
      coreConcepts: '그루밍 기준, 표정·자세, 기본 응대 매너',
      teachingHint: '그루밍 기준 강의 및 시범',
      studentHint: '짝 활동으로 인사·응대 자세 실습',
      practiceHint: '이미지 메이킹 자가진단 실습',
      aiUsageHint: 'AI로 상황별 표준 인사 멘트 초안 생성',
    },
    {
      title: '표준 서비스 화법',
      coreConcepts: '존댓말 응대, 상황별 표준 멘트, 목소리 톤 관리',
      teachingHint: '표준 화법 강의 및 롤플레이 시범',
      studentHint: '2인 1조 표준 화법 역할극',
      practiceHint: '고객 응대 시나리오 대본 작성',
      aiUsageHint: 'AI로 상황별 표준 응대 대본 초안 생성',
    },
    {
      title: '고객 유형별 응대 전략',
      coreConcepts: '고객 세분화, 문화적 다양성, 특별 승객 응대',
      teachingHint: '고객 유형 분류 및 응대 전략 강의',
      studentHint: '고객 유형별 응대 시나리오 롤플레이',
      practiceHint: '문화권별 응대 매너 조사 실습',
      aiUsageHint: 'AI로 문화권별 응대 유의사항 요약표 생성',
    },
    {
      title: '컴플레인 처리와 서비스 회복',
      coreConcepts: '컴플레인 유형, 서비스 회복 전략, 사과와 보상 원칙',
      teachingHint: '서비스 회복 이론 강의 및 사례 분석',
      studentHint: '컴플레인 시나리오 역할극',
      practiceHint: '컴플레인 대응 스크립트 작성 실습',
      aiUsageHint: 'AI로 컴플레인 유형별 대응 스크립트 초안 생성',
    },
    {
      title: '기내 안전 절차의 기초',
      coreConcepts: '비상구 작동, 안전 브리핑, 승객 안전 확인',
      teachingHint: '기내 안전 절차 이론 강의',
      studentHint: '안전 브리핑 시연 실습',
      practiceHint: '안전 점검 체크리스트 작성',
      aiUsageHint: 'AI로 안전 브리핑 스크립트 초안 생성(교수자 검증 필수)',
    },
    {
      title: '비상 상황 대응 시뮬레이션',
      coreConcepts: '비상 대응 절차, 승무원 간 협업(CRM), 승객 안내',
      teachingHint: '비상 대응 시나리오 강의 및 시범',
      studentHint: '조별 비상 상황 시뮬레이션',
      practiceHint: '비상 대응 절차 순서도 작성',
      aiUsageHint: 'AI로 비상 상황 절차 요약카드 생성 후 교수자 검증',
    },
    {
      title: '고객경험(CX) 설계',
      coreConcepts: '고객여정지도(Customer Journey Map), 접점 관리, 경험 디자인',
      teachingHint: '고객경험 설계 이론 강의',
      studentHint: '조별 고객여정지도 작성 실습',
      practiceHint: '접점별 서비스 개선안 도출',
      aiUsageHint: 'AI로 고객여정지도 초안 생성',
    },
    {
      title: '팀워크와 승무원 협업(CRM)',
      coreConcepts: 'Crew Resource Management, 의사소통, 역할 분담',
      teachingHint: 'CRM 이론 강의 및 사례 분석',
      studentHint: '조별 협업 시뮬레이션',
      practiceHint: '협업 상황 역할 분담 실습',
      aiUsageHint: 'AI로 CRM 상황별 의사소통 가이드 초안 생성',
    },
    {
      title: '항공 서비스 트렌드와 디지털 전환',
      coreConcepts: '비대면 서비스, 디지털 체크인, 서비스 혁신 사례',
      teachingHint: '최신 서비스 트렌드 강의',
      studentHint: '조별 서비스 혁신 사례 조사',
      practiceHint: '트렌드 반영 서비스 아이디어 발표',
      aiUsageHint: 'AI로 최신 서비스 트렌드 요약 자료 생성',
    },
    {
      title: '종합 서비스 시뮬레이션',
      coreConcepts: '탑승부터 하기까지 전체 서비스 프로세스 통합',
      teachingHint: '종합 시뮬레이션 시나리오 안내',
      studentHint: '조별 전 과정 롤플레이 및 상호 평가',
      practiceHint: '종합 시뮬레이션 체크리스트 평가',
      aiUsageHint: 'AI로 종합 시뮬레이션 평가 체크리스트 생성',
    },
  ],
  aiTools: [
    {
      name: 'AI 스크립트 생성기(범용 LLM 챗봇)',
      purpose: '고객 응대·컴플레인 대응 스크립트 초안 생성',
      instructorUse: '생성된 스크립트를 실제 항공사 서비스 규정과 대조 검토 후 배포',
      studentUse: '롤플레이 연습용 대본 초안으로 활용',
      caution: '실제 승객 개인정보나 특정 항공사 내부 규정을 입력하지 않는다',
      alternative: '항공사 서비스 매뉴얼, 관광서비스학 교재',
    },
  ],
  practiceNamesPool: [
    '표준 화법 롤플레이',
    '컴플레인 대응 시뮬레이션',
    '기내 안전 브리핑 실습',
    '고객여정지도 작성 워크숍',
  ],
  caseScenarioPool: [
    '기내식 오류로 불만을 제기하는 승객 응대 사례',
    '난기류 상황에서 승객 안전을 확인하는 사례',
    '문화적 배경이 다른 승객의 특별 요청 응대 사례',
    '수하물 분실로 인한 컴플레인 처리 사례',
  ],
  projectThemePool: [
    '신규 노선 승객경험 개선 기획안 제작',
    '컴플레인 대응 매뉴얼 개발',
    '특별 승객(고령자·장애인·유아 동반) 응대 가이드 제작',
  ],
  ethicsNotesPool: [
    '롤플레이 시나리오에 실제 승객이나 특정 인물을 특정하지 않는다',
    '안전 절차 관련 AI 생성 내용은 반드시 공식 지침으로 재검증한다',
  ],
  vocabulary: ['승객', '기내', '서비스 회복', '고객경험', '그루밍', 'CRM'],
}
