import type { DomainPack } from './types'

export const businessServicePack: DomainPack = {
  id: 'businessService',
  label: '경영·서비스경영',
  matchKeywords: ['서비스경영', '경영', '마케팅', '고객', '창업', '유통', '전략', '비즈니스'],
  courseNatureTemplate:
    '이론적 프레임워크(가치사슬, 서비스 품질 모델 등)를 실제 기업·업종 사례에 적용해 분석·제안하는 능력을 기르는 과목이다. 정답이 하나가 아닌 사례 기반 의사결정 훈련의 비중이 크다.',
  studentCharacteristics:
    '실제 기업 사례와 데이터를 다룰 때 몰입도가 높으며, 조별 토론·발표를 통한 협업 학습에 익숙하다. 이론을 암기하기보다 사례에 적용해보는 과정에서 이해도가 높아진다.',
  prerequisitesPool: ['경영학원론 기초 개념', '기초 통계·수치 해석 능력', '조별 발표 경험'],
  coreConcepts: [
    '서비스 품질 모델(SERVQUAL)',
    '고객가치와 고객만족',
    '서비스 접점(MOT, Moment of Truth)',
    '서비스 실패와 회복 전략',
    '가치사슬 분석',
    '고객관계관리(CRM)',
    '서비스 디자인·프로세스 설계',
    '데이터 기반 의사결정',
  ],
  difficultiesPool: [
    '추상적인 경영 프레임워크를 실제 사례에 연결하는 데 어려움을 느낌',
    '조별 프로젝트에서 무임승차 문제로 학습 형평성 저하',
    '정량 데이터 해석과 정성적 통찰을 함께 다루는 균형이 어려움',
    '실제 기업 최신 사례 정보 접근의 제약',
  ],
  aiApplicability:
    'AI는 기업 사례 요약, SWOT/가치사슬 초안 작성, 설문·인터뷰 질문지 초안 생성 등 분석 보조 도구로 유효하다. 다만 최신 시장 데이터나 재무 수치는 반드시 공식 출처로 재확인해야 한다.',
  instructorJudgmentPool: [
    'AI가 요약한 기업 사례의 사실관계 최종 확인',
    '조별 프로젝트 주제의 난이도·범위 적절성 판단',
    'AI 생성 설문 문항의 편향 여부 검토',
  ],
  weekTopics: [
    {
      title: '서비스 경제와 산업 구조',
      coreConcepts: '서비스 경제화, 서비스업 분류, 서비스 특성(무형성·비분리성)',
      teachingHint: '서비스 산업 개관 강의',
      studentHint: '업종별 서비스 특성 조사 및 발표',
      practiceHint: '서비스 특성 분석 워크시트 작성',
      aiUsageHint: 'AI로 업종별 서비스 특성 비교표 초안 생성',
    },
    {
      title: '고객가치와 고객만족',
      coreConcepts: '고객가치 방정식, 고객만족 결정요인, 기대-성과 불일치 모델',
      teachingHint: '고객가치 이론 강의',
      studentHint: '조별 고객가치 사례 분석',
      practiceHint: '고객가치 방정식 적용 실습',
      aiUsageHint: 'AI로 산업별 고객가치 요소 브레인스토밍 초안 생성',
    },
    {
      title: '서비스 품질 모델(SERVQUAL)',
      coreConcepts: 'SERVQUAL 5개 차원, 품질 갭 모델',
      teachingHint: 'SERVQUAL 모델 강의 및 적용 사례',
      studentHint: '조별로 특정 기업 서비스 품질 진단',
      practiceHint: 'SERVQUAL 설문 문항 설계 실습',
      aiUsageHint: 'AI로 SERVQUAL 설문 문항 초안 생성 후 교수자 검토',
    },
    {
      title: '서비스 접점(MOT) 관리',
      coreConcepts: 'Moment of Truth, 고객여정지도, 접점별 만족 요인',
      teachingHint: 'MOT 개념 강의 및 사례 시연',
      studentHint: '조별 고객여정지도 작성',
      practiceHint: '접점별 개선안 도출 워크숍',
      aiUsageHint: 'AI로 고객여정지도 초안 생성',
    },
    {
      title: '서비스 실패와 회복 전략',
      coreConcepts: '서비스 실패 유형, 회복 패러독스, 보상 전략',
      teachingHint: '서비스 회복 이론 강의 및 사례 분석',
      studentHint: '조별 서비스 실패 사례 분석 및 회복안 제안',
      practiceHint: '컴플레인 대응 시나리오 작성',
      aiUsageHint: 'AI로 서비스 실패 사례 요약 및 대응안 브레인스토밍',
    },
    {
      title: '가치사슬 분석',
      coreConcepts: '포터의 가치사슬, 본원적 활동과 지원 활동',
      teachingHint: '가치사슬 프레임워크 강의',
      studentHint: '조별 기업 가치사슬 분석 실습',
      practiceHint: '가치사슬 다이어그램 작성',
      aiUsageHint: 'AI로 가치사슬 다이어그램 초안 생성',
    },
    {
      title: '고객관계관리(CRM) 전략',
      coreConcepts: 'CRM 개념, 고객 세분화, 충성도 프로그램',
      teachingHint: 'CRM 전략 강의 및 사례 소개',
      studentHint: '조별 CRM 전략 제안서 작성',
      practiceHint: '고객 세분화 기준 설계 실습',
      aiUsageHint: 'AI로 고객 세분화 기준 초안 브레인스토밍',
    },
    {
      title: '서비스 프로세스 설계',
      coreConcepts: '서비스 청사진(Service Blueprint), 프로세스 표준화',
      teachingHint: '서비스 청사진 작성법 강의',
      studentHint: '조별 서비스 청사진 작성 실습',
      practiceHint: '프로세스 병목 지점 분석',
      aiUsageHint: 'AI로 서비스 청사진 초안 생성',
    },
    {
      title: '데이터 기반 서비스 의사결정',
      coreConcepts: '고객 데이터 분석, KPI 설계, 대시보드 활용',
      teachingHint: '데이터 기반 의사결정 사례 강의',
      studentHint: '조별 KPI 설계 실습',
      practiceHint: '샘플 데이터로 지표 해석 실습',
      aiUsageHint: 'AI로 KPI 후보 목록 브레인스토밍',
    },
    {
      title: '디지털 전환과 서비스 혁신',
      coreConcepts: '비대면 서비스, 플랫폼 비즈니스, 서비스 혁신 사례',
      teachingHint: '디지털 전환 사례 강의',
      studentHint: '조별 서비스 혁신 사례 조사 발표',
      practiceHint: '혁신 아이디어 도출 워크숍',
      aiUsageHint: 'AI로 최신 서비스 혁신 사례 요약 자료 생성',
    },
    {
      title: '서비스 전략 종합 사례 분석',
      coreConcepts: '앞선 개념들의 통합 적용, 전략 제안서 작성',
      teachingHint: '종합 사례 분석 가이드',
      studentHint: '조별 최종 프로젝트 초안 발표 및 상호 피드백',
      practiceHint: '전략 제안서 초안 작성',
      aiUsageHint: 'AI로 전략 제안서 목차 및 개요 초안 생성',
    },
  ],
  aiTools: [
    {
      name: 'AI 사례 요약 도우미(범용 LLM 챗봇)',
      purpose: '기업 사례·기사 요약 및 SWOT 초안 작성',
      instructorUse: '요약 내용의 사실관계와 최신성을 검토 후 강의 자료로 활용',
      studentUse: '조별 과제 준비 시 자료 정리 보조 도구로 활용',
      caution: '최신 재무·시장 데이터는 반드시 공식 출처로 재확인',
      alternative: '기업 공시자료, 산업 보고서',
    },
  ],
  practiceNamesPool: [
    'SERVQUAL 진단 실습',
    '고객여정지도 워크숍',
    '서비스 청사진 작성 실습',
    'CRM 전략 제안 워크숍',
  ],
  caseScenarioPool: [
    '온라인 주문 배송 지연으로 인한 고객 불만 사례',
    '멤버십 등급 개편에 대한 고객 반발 사례',
    '경쟁사 대비 서비스 차별화에 실패한 사례',
    '고객 데이터 오류로 발생한 서비스 사고 사례',
  ],
  projectThemePool: [
    '지역 소상공인을 위한 서비스 개선 제안',
    '신규 서비스 런칭 기획안 작성',
    '고객 이탈 방지를 위한 CRM 전략 수립',
  ],
  ethicsNotesPool: [
    '실제 기업 사례 분석 시 저작권과 출처 표기를 명확히 한다',
    'AI가 생성한 시장 수치는 반드시 공식 자료로 검증한다',
  ],
  vocabulary: ['고객가치', '서비스 접점', '고객여정', 'CRM', '가치사슬', '서비스 회복'],
}
