import type { DomainPack } from './types'

export const christianEducationPack: DomainPack = {
  id: 'christianEducation',
  label: '기독교교육·신학',
  matchKeywords: ['기독교', '신앙', '성경', '신학', '목회', '교회', '선교'],
  courseNatureTemplate:
    '지식 습득을 넘어 개인의 신앙 성찰과 공동체적 실천으로 이어지는 것을 지향하는 과목이다. 성경 본문에 대한 학문적 이해와 삶에 대한 신앙적 적용이 함께 다뤄져야 한다.',
  studentCharacteristics:
    '개인의 신앙 배경과 경험이 학습에 큰 영향을 미치며, 강의식 전달보다 나눔·성찰·공동체 활동에서 몰입도가 높다. 다양한 신앙 배경(초신자~기성 신자)을 가진 학생이 함께 수업을 듣는 경우가 많다.',
  prerequisitesPool: ['성경 개관에 대한 기초 이해', '기본적인 기독교 교리 이해', '소그룹 나눔 경험'],
  coreConcepts: [
    '성경 해석학의 기초',
    '신앙 성찰과 영성 형성',
    '공동체 학습(코이노니아)',
    '신학적 성찰과 삶의 통합',
    '기독교 세계관',
    '섬김과 실천(디아코니아)',
    '기도와 묵상의 실제',
    '세대 간 신앙 전수',
  ],
  difficultiesPool: [
    '학생 간 신앙 배경 편차로 수업 참여도 차이가 큼',
    '본문에 대한 학문적 해석과 개인적 적용을 균형 있게 다루기 어려움',
    '나눔 활동에서 개인의 신앙 이야기를 공개하는 부담감',
    '이론적 신학 개념을 실생활 언어로 풀어내기 어려움',
  ],
  aiApplicability:
    'AI는 본문 배경 자료 정리, 토론 질문 초안, 묵상 가이드 구조화에 보조적으로 활용할 수 있다. 다만 신앙적 해석과 적용, 개인 신앙 나눔의 지도는 반드시 교수자(목회자)의 신학적 관점과 공동체 맥락에서 이뤄져야 한다.',
  instructorJudgmentPool: [
    'AI가 정리한 본문 배경 자료의 신학적 관점 편향 여부 확인',
    '나눔 활동에서 학생 개인정보·신앙고백의 민감성 보호',
    '토론 질문이 특정 교단 신학에 치우치지 않았는지 검토',
  ],
  weekTopics: [
    {
      title: '성경 해석의 기초',
      coreConcepts: '본문·상황·적용의 해석 원리, 성경 각 권의 배경',
      teachingHint: '성경 해석학 기초 강의',
      studentHint: '조별 본문 배경 조사 및 나눔',
      practiceHint: '본문 분석 워크시트 작성',
      aiUsageHint: 'AI로 본문의 역사적·문화적 배경 자료 초안 정리(교수자 검토 후 사용)',
    },
    {
      title: '기독교 세계관의 이해',
      coreConcepts: '창조-타락-구속-회복의 서사, 세계관 비교',
      teachingHint: '기독교 세계관 강의',
      studentHint: '조별 세계관 비교 토론',
      practiceHint: '세계관 적용 사례 나눔',
      aiUsageHint: 'AI로 세계관 비교 토론 질문 초안 생성',
    },
    {
      title: '신앙 성찰과 영성 형성',
      coreConcepts: '영성 형성의 단계, 개인 신앙 여정 돌아보기',
      teachingHint: '영성 형성 이론 강의',
      studentHint: '개인 신앙 여정 성찰 글쓰기',
      practiceHint: '성찰 저널 작성 실습',
      aiUsageHint: 'AI로 성찰 글쓰기를 위한 질문 프롬프트 초안 생성',
    },
    {
      title: '기도와 묵상의 실제',
      coreConcepts: '묵상(QT)의 방법, 기도의 유형',
      teachingHint: '묵상 방법론 강의 및 시범',
      studentHint: '조별 묵상 나눔 실습',
      practiceHint: '개인 묵상 가이드 작성',
      aiUsageHint: 'AI로 주간 묵상 가이드 구조 초안 생성',
    },
    {
      title: '공동체 학습(코이노니아)',
      coreConcepts: '초대교회 공동체성, 소그룹 나눔의 원리',
      teachingHint: '공동체성 이론 강의',
      studentHint: '소그룹 나눔 실습 및 상호 피드백',
      practiceHint: '공동체 활동 기획 워크숍',
      aiUsageHint: 'AI로 소그룹 나눔 질문 목록 초안 생성',
    },
    {
      title: '신학적 성찰과 삶의 통합',
      coreConcepts: '신학과 일상의 연결, 실천신학적 접근',
      teachingHint: '신학적 성찰 방법론 강의',
      studentHint: '조별 사례 기반 신학적 토론',
      practiceHint: '삶의 현장 적용 사례 나눔',
      aiUsageHint: 'AI로 토론 사례 시나리오 초안 생성',
    },
    {
      title: '섬김과 실천(디아코니아)',
      coreConcepts: '섬김의 신학적 의미, 지역사회 실천 사례',
      teachingHint: '디아코니아 신학 강의',
      studentHint: '조별 섬김 실천 계획 수립',
      practiceHint: '지역사회 섬김 활동 기획 워크숍',
      aiUsageHint: 'AI로 섬김 실천 아이디어 브레인스토밍 초안 생성',
    },
    {
      title: '세대 간 신앙 전수',
      coreConcepts: '가정 신앙교육, 세대 간 소통',
      teachingHint: '세대 간 신앙 전수 사례 강의',
      studentHint: '조별 가정 신앙교육 사례 나눔',
      practiceHint: '세대 간 대화 시나리오 작성',
      aiUsageHint: 'AI로 세대 간 대화 시나리오 초안 생성',
    },
    {
      title: '다양성과 포용의 신앙 공동체',
      coreConcepts: '다양한 배경의 구성원 포용, 공동체 갈등 다루기',
      teachingHint: '포용적 공동체 사례 강의',
      studentHint: '조별 공동체 갈등 사례 토론',
      practiceHint: '갈등 조정 역할극',
      aiUsageHint: 'AI로 공동체 갈등 시나리오 초안 생성',
    },
    {
      title: '기독교 교육과정 설계 기초',
      coreConcepts: '연령별 교육 목표, 커리큘럼 설계 원리',
      teachingHint: '교육과정 설계 이론 강의',
      studentHint: '조별 연령별 교육안 초안 작성',
      practiceHint: '교육안 발표 및 상호 피드백',
      aiUsageHint: 'AI로 연령별 교육안 목차 초안 생성',
    },
    {
      title: '신앙 실천 프로젝트 준비',
      coreConcepts: '학습 내용의 통합적 적용, 실천 계획 구체화',
      teachingHint: '최종 프로젝트 가이드 강의',
      studentHint: '조별 실천 프로젝트 계획서 작성',
      practiceHint: '프로젝트 발표 리허설',
      aiUsageHint: 'AI로 프로젝트 계획서 구조 초안 생성',
    },
  ],
  aiTools: [
    {
      name: 'AI 자료 정리 도우미(범용 LLM 챗봇)',
      purpose: '본문 배경 자료, 토론 질문, 묵상 가이드 구조 초안 생성',
      instructorUse: '생성된 자료의 신학적 관점을 검토하고 교단·공동체 맥락에 맞게 수정',
      studentUse: '개인 묵상·과제 준비를 위한 참고 자료로만 활용, 최종 해석은 스스로 성찰',
      caution: '개인 신앙 고백이나 민감한 나눔 내용을 AI에 입력하지 않는다',
      alternative: '성경 주석서, 신학 사전, 목회자·교수자 상담',
    },
  ],
  practiceNamesPool: ['소그룹 나눔 실습', '묵상 가이드 작성 워크숍', '섬김 실천 기획 워크숍', '세대 간 대화 역할극'],
  caseScenarioPool: [
    '신앙 배경이 다른 학생들이 함께하는 소그룹 나눔 사례',
    '지역사회 섬김 활동 중 발생한 갈등 조정 사례',
    '신앙과 진로 고민이 겹치는 학생 상담 사례',
  ],
  projectThemePool: ['지역사회 섬김 프로젝트 기획', '세대 간 신앙 전수 프로그램 설계', '소그룹 나눔 커리큘럼 제작'],
  ethicsNotesPool: [
    '학생 개인의 신앙고백이나 사적 나눔 내용을 동의 없이 공개하지 않는다',
    'AI 생성 자료는 특정 교단 신학에 편향되지 않았는지 교수자가 검토한다',
  ],
  vocabulary: ['성경 이해', '신앙성찰', '공동체 학습', '영성', '섬김', '묵상'],
}
