import type { DomainPack } from './types'

export const computingPack: DomainPack = {
  id: 'computing',
  label: 'IT·컴퓨터공학',
  matchKeywords: ['프로그래밍', '컴퓨터', '소프트웨어', '데이터', 'ai', '인공지능', '알고리즘', '코딩', '개발'],
  courseNatureTemplate:
    '이론(개념·원리)과 실습(코드 작성·디버깅)이 밀접하게 연결된 과목으로, 매주 누적되는 개념 위에 실습 난이도가 점진적으로 높아진다. 직접 작성하고 실행해보는 과정 없이는 이해도가 낮게 형성된다.',
  studentCharacteristics:
    '실습 환경(개발 도구, 실행 결과)에서 즉각적인 피드백을 받을 때 학습 효과가 높으며, 개념을 코드로 직접 구현해보는 과제에서 몰입도가 크다. 사전 프로그래밍 경험 편차가 학습 속도에 큰 영향을 준다.',
  prerequisitesPool: ['기초 논리적 사고력', '컴퓨터 기본 조작 능력', '기초 수학(집합, 함수 개념)'],
  coreConcepts: [
    '변수와 자료형',
    '제어 구조(조건문·반복문)',
    '함수와 모듈화',
    '자료구조 기초',
    '디버깅과 예외 처리',
    'AI 도구를 활용한 코드 이해·리뷰',
    '버전 관리(협업 도구)',
    '알고리즘 복잡도 개념',
  ],
  difficultiesPool: [
    '문법 오류와 논리 오류를 구분하지 못해 디버깅에 시간이 오래 걸림',
    '추상적 개념(재귀, 포인터 등)을 시각적으로 이해하기 어려움',
    'AI 코드 생성 도구에 지나치게 의존해 원리를 이해하지 않고 넘어가는 경향',
    '실습 환경 설정 단계에서부터 좌절하는 학생 발생',
  ],
  aiApplicability:
    'AI 코드 어시스턴트는 예제 코드 생성, 오류 원인 설명, 코드 리뷰 보조에 강력하지만, 학생이 원리를 이해하지 못한 채 결과만 복사하는 것을 방지하는 장치(직접 설명하기, AI 답변 검증 과제 등)가 함께 필요하다.',
  instructorJudgmentPool: [
    'AI가 생성한 코드의 정확성과 실습 환경 호환성 사전 검증',
    '학생의 AI 의존도와 실제 이해도 간 괴리 여부 확인',
    '실습 난이도가 매주 누적 개념을 따라가는지 점검',
  ],
  weekTopics: [
    {
      title: '개발 환경 설정과 기초 문법',
      coreConcepts: '개발 도구 설치, 변수와 자료형, 출력 함수',
      teachingHint: '개발 환경 설정 시연 및 기초 문법 강의',
      studentHint: '개발 환경 설정 및 첫 프로그램 작성 실습',
      practiceHint: '간단한 입출력 프로그램 작성',
      aiUsageHint: 'AI로 환경설정 오류 해결 힌트 생성(직접 해결 우선, AI는 보조)',
    },
    {
      title: '조건문과 논리적 사고',
      coreConcepts: '조건문, 논리 연산자, 분기 설계',
      teachingHint: '조건문 강의 및 예제 시연',
      studentHint: '조건문 활용 미니 프로그램 작성',
      practiceHint: '조건 분기 설계 실습',
      aiUsageHint: 'AI로 조건문 예제 생성 후 직접 손코딩으로 재구현',
    },
    {
      title: '반복문과 알고리즘 기초',
      coreConcepts: '반복문, 누적 계산, 반복 종료 조건',
      teachingHint: '반복문 강의 및 트레이싱 시연',
      studentHint: '반복문 활용 프로그램 작성 실습',
      practiceHint: '반복문 트레이싱 워크시트',
      aiUsageHint: 'AI로 반복문 동작 과정 시각화 설명 생성',
    },
    {
      title: '함수와 모듈화',
      coreConcepts: '함수 정의·호출, 매개변수와 반환값, 코드 재사용',
      teachingHint: '함수 설계 원칙 강의',
      studentHint: '기능 단위 함수 분리 실습',
      practiceHint: '함수 리팩터링 실습',
      aiUsageHint: 'AI로 중복 코드를 함수로 리팩터링하는 예시 생성',
    },
    {
      title: '자료구조 기초(리스트·딕셔너리)',
      coreConcepts: '리스트, 딕셔너리, 자료 탐색·정렬 기초',
      teachingHint: '자료구조 개념 강의 및 시각화',
      studentHint: '자료구조 활용 미니 프로젝트',
      practiceHint: '데이터 처리 실습',
      aiUsageHint: 'AI로 자료구조 선택 이유 설명 생성',
    },
    {
      title: '디버깅과 예외 처리',
      coreConcepts: '오류 유형 분류, 예외 처리 구문, 디버깅 전략',
      teachingHint: '디버깅 전략 강의 및 시연',
      studentHint: '의도된 오류 코드 디버깅 실습',
      practiceHint: '예외 처리 코드 작성 실습',
      aiUsageHint: 'AI로 오류 메시지 해석 및 원인 설명 생성(학생이 직접 수정)',
    },
    {
      title: 'AI 코드 어시스턴트 활용법',
      coreConcepts: 'AI 코드 생성 도구의 원리와 한계, 프롬프트 작성법',
      teachingHint: 'AI 코드 도구 활용 및 검증 방법 강의',
      studentHint: 'AI 생성 코드를 직접 검증·수정하는 실습',
      practiceHint: 'AI 답변 검증 체크리스트 적용 실습',
      aiUsageHint: 'AI가 생성한 코드의 오류를 학생이 직접 찾아 수정',
    },
    {
      title: '협업 도구와 버전 관리',
      coreConcepts: '버전 관리 개념, 협업 워크플로 기초',
      teachingHint: '버전 관리 도구 강의 및 시연',
      studentHint: '조별 협업 실습',
      practiceHint: '버전 관리 기본 명령 실습',
      aiUsageHint: 'AI로 협업 워크플로 요약 가이드 생성',
    },
    {
      title: '알고리즘 복잡도 기초',
      coreConcepts: '시간 복잡도 개념, 효율적 코드 설계',
      teachingHint: '복잡도 개념 강의 및 비교 시연',
      studentHint: '동일 문제의 다른 풀이 비교 실습',
      practiceHint: '복잡도 비교 워크시트 작성',
      aiUsageHint: 'AI로 서로 다른 풀이의 복잡도 비교 설명 생성',
    },
    {
      title: '미니 프로젝트 설계',
      coreConcepts: '요구사항 분석, 기능 명세, 설계 문서 작성',
      teachingHint: '프로젝트 설계 방법론 강의',
      studentHint: '조별 프로젝트 기획 및 설계',
      practiceHint: '설계 문서 작성 실습',
      aiUsageHint: 'AI로 요구사항 명세서 초안 생성',
    },
    {
      title: '테스트와 코드 품질',
      coreConcepts: '테스트 케이스 작성, 코드 가독성, 리뷰 문화',
      teachingHint: '테스트·코드 품질 강의',
      studentHint: '조별 코드 리뷰 실습',
      practiceHint: '테스트 케이스 작성 실습',
      aiUsageHint: 'AI로 테스트 케이스 후보 목록 생성',
    },
  ],
  aiTools: [
    {
      name: 'AI 코드 어시스턴트',
      purpose: '예제 코드 생성, 오류 설명, 코드 리뷰 보조',
      instructorUse: '학생 제출 코드와 AI 생성 코드를 비교해 이해도 평가 설계에 반영',
      studentUse: '막힌 부분의 힌트로 활용하되, 반드시 직접 손코딩으로 재구현',
      caution: '결과를 그대로 제출하지 않고 원리를 설명할 수 있어야 함(AI 답변 검증 체크리스트 필수)',
      alternative: '공식 문서, 교재 예제',
    },
  ],
  practiceNamesPool: ['페어 프로그래밍 실습', 'AI 코드 검증 실습', '디버깅 챌린지', '미니 프로젝트 스프린트'],
  caseScenarioPool: [
    'AI가 생성한 코드에 숨어있는 논리 오류를 찾아내는 사례',
    '협업 중 발생한 코드 충돌을 해결하는 사례',
    '비효율적인 코드를 리팩터링하는 사례',
  ],
  projectThemePool: ['생활 문제 해결 프로그램 제작', '데이터 처리 자동화 도구 제작', '팀 협업용 미니 서비스 제작'],
  ethicsNotesPool: [
    'AI 생성 코드를 그대로 제출하지 않고 반드시 이해·검증 과정을 거친다',
    '오픈소스 코드 사용 시 라이선스와 출처를 명시한다',
  ],
  vocabulary: ['알고리즘', '디버깅', '함수', '자료구조', 'AI 코드 어시스턴트', '리팩터링'],
}
