import type { DomainPack } from './types'

export const educationPack: DomainPack = {
  id: 'education',
  label: '교육학·유아·특수교육',
  matchKeywords: ['교육학', '유아교육', '특수교육', '보육', '교육과정', '교수법', '아동'],
  courseNatureTemplate:
    '학습자 발달 이해와 교육 현장 실습이 함께 요구되는 과목으로, 이론적 발달 단계 지식을 실제 지도안·활동 설계로 구현하는 능력을 기른다.',
  studentCharacteristics:
    '실제 현장 사례와 지도안 작성 실습에서 학습 동기가 높으며, 발달 단계별 특성을 자신의 경험과 연결지어 이해하려는 경향이 있다.',
  prerequisitesPool: ['발달심리학 기초 개념', '교육학개론 수준의 이해', '관찰·기록 기초 소양'],
  coreConcepts: [
    '발달 단계 이론',
    '교육과정 설계 원리',
    '학습자 중심 교수법',
    '평가와 관찰 기록',
    '개별화 교육(IEP) 개념',
    '놀이·활동 중심 학습',
    '가정-기관 연계',
    '교육 현장 윤리',
  ],
  difficultiesPool: [
    '이론적 발달 단계를 실제 아동·학습자 관찰과 연결하기 어려움',
    '지도안 작성 시 이론적 근거와 실행 가능성의 균형을 맞추기 어려움',
    '개별 학습자의 다양성을 고려한 설계 경험 부족',
    '현장 실습 기회의 제한으로 이론 중심 학습에 머무르기 쉬움',
  ],
  aiApplicability:
    'AI는 활동 아이디어 브레인스토밍, 지도안 초안 구조화, 관찰 기록 양식 생성에 유용하다. 다만 실제 아동·학습자에 대한 평가와 지도는 반드시 교수자·현장 전문가의 판단을 거쳐야 한다.',
  instructorJudgmentPool: [
    'AI가 생성한 지도안이 발달 단계에 적합한지 검토',
    '개별화 교육 관련 내용의 전문성·윤리성 확인',
    '실제 아동 관찰 기록에 개인정보가 포함되지 않았는지 점검',
  ],
  weekTopics: [
    {
      title: '발달 단계 이론의 이해',
      coreConcepts: '인지·정서·사회성 발달 단계, 주요 발달 이론가',
      teachingHint: '발달 이론 개관 강의',
      studentHint: '조별 발달 단계 사례 토론',
      practiceHint: '발달 단계 체크리스트 작성',
      aiUsageHint: 'AI로 발달 단계별 특징 요약표 초안 생성',
    },
    {
      title: '교육과정 설계의 원리',
      coreConcepts: '교육목표 설정, 교육과정 구성 원리',
      teachingHint: '교육과정 설계 이론 강의',
      studentHint: '조별 교육과정 개요 작성',
      practiceHint: '교육목표 진술 실습',
      aiUsageHint: 'AI로 교육목표 진술문 초안 생성',
    },
    {
      title: '학습자 중심 교수법',
      coreConcepts: '학습자 중심 수업 설계, 참여형 교수법',
      teachingHint: '학습자 중심 교수법 강의 및 사례',
      studentHint: '조별 참여형 활동 설계',
      practiceHint: '활동 계획서 작성 실습',
      aiUsageHint: 'AI로 참여형 활동 아이디어 브레인스토밍',
    },
    {
      title: '놀이·활동 중심 학습',
      coreConcepts: '놀이의 교육적 의미, 활동 중심 학습 설계',
      teachingHint: '놀이 중심 학습 이론 강의',
      studentHint: '조별 놀이 활동 설계 및 시연',
      practiceHint: '활동 자료 제작 실습',
      aiUsageHint: 'AI로 연령별 놀이 활동 아이디어 목록 생성',
    },
    {
      title: '관찰과 기록의 방법',
      coreConcepts: '관찰 기법, 발달 기록 양식, 객관적 서술',
      teachingHint: '관찰 기록 방법론 강의',
      studentHint: '모의 관찰 기록 실습',
      practiceHint: '관찰 기록지 작성 연습',
      aiUsageHint: 'AI로 관찰 기록 양식 초안 생성',
    },
    {
      title: '개별화 교육(IEP)의 이해',
      coreConcepts: '개별화 교육계획, 학습자 다양성 대응',
      teachingHint: '개별화 교육 이론 강의',
      studentHint: '조별 개별화 교육 사례 분석',
      practiceHint: 'IEP 초안 작성 실습',
      aiUsageHint: 'AI로 IEP 목표 진술 초안 생성 후 전문가 검토 필요성 강조',
    },
    {
      title: '지도안 작성의 실제',
      coreConcepts: '지도안 구성 요소, 활동-평가 연계',
      teachingHint: '지도안 작성법 강의 및 예시 시연',
      studentHint: '조별 지도안 작성 실습',
      practiceHint: '지도안 상호 검토 워크숍',
      aiUsageHint: 'AI로 지도안 구조 초안 생성',
    },
    {
      title: '가정-기관 연계 및 소통',
      coreConcepts: '가정 연계 활동, 보호자 소통 전략',
      teachingHint: '가정 연계 사례 강의',
      studentHint: '조별 가정통신문 작성 실습',
      practiceHint: '소통 시나리오 역할극',
      aiUsageHint: 'AI로 가정통신문 초안 생성',
    },
    {
      title: '교육 현장 윤리와 안전',
      coreConcepts: '아동학대 예방, 안전관리, 교육자 윤리',
      teachingHint: '현장 윤리·안전 강의',
      studentHint: '조별 윤리 딜레마 사례 토론',
      practiceHint: '안전관리 체크리스트 작성',
      aiUsageHint: 'AI로 안전관리 체크리스트 초안 생성',
    },
    {
      title: '평가와 피드백 설계',
      coreConcepts: '형성평가, 발달 기반 피드백',
      teachingHint: '평가 설계 이론 강의',
      studentHint: '조별 평가 도구 설계 실습',
      practiceHint: '피드백 문구 작성 실습',
      aiUsageHint: 'AI로 발달 단계별 피드백 문구 초안 생성',
    },
    {
      title: '현장 실습 사례 종합',
      coreConcepts: '학습 내용의 통합적 적용, 실습 성찰',
      teachingHint: '종합 사례 발표 가이드',
      studentHint: '조별 최종 지도안 발표 및 상호 피드백',
      practiceHint: '실습 성찰 저널 작성',
      aiUsageHint: 'AI로 성찰 저널 작성을 위한 질문 프롬프트 생성',
    },
  ],
  aiTools: [
    {
      name: 'AI 활동안 도우미(범용 LLM 챗봇)',
      purpose: '활동 아이디어, 지도안 구조, 관찰 기록 양식 초안 생성',
      instructorUse: '생성된 지도안이 발달 단계와 교육과정 기준에 맞는지 검토 후 활용',
      studentUse: '지도안 작성의 출발점으로 활용하되 반드시 현장 적합성 검토',
      caution: '실제 아동·학습자의 개인정보나 관찰 기록 원문을 입력하지 않는다',
      alternative: '표준보육과정, 교육과정 해설서',
    },
  ],
  practiceNamesPool: ['지도안 작성 워크숍', '놀이 활동 설계 실습', '관찰 기록 실습', '가정통신문 작성 실습'],
  caseScenarioPool: [
    '발달이 또래보다 느린 아동을 위한 개별화 지도 사례',
    '가정과의 소통 갈등을 해결하는 사례',
    '안전사고 예방을 위한 환경 점검 사례',
  ],
  projectThemePool: ['연령별 활동 프로그램 개발', '개별화 교육계획(IEP) 초안 작성', '가정 연계 프로그램 기획'],
  ethicsNotesPool: [
    '실제 아동·학습자의 이름이나 개인 식별 정보를 사례에 포함하지 않는다',
    'AI가 생성한 개별화 교육 관련 내용은 반드시 전문가 검토를 거친다',
  ],
  vocabulary: ['발달 단계', '지도안', '개별화 교육', '관찰 기록', '놀이 중심', '가정 연계'],
}
