import type { DomainPack } from './types'

export const nursingPack: DomainPack = {
  id: 'nursing',
  label: '간호·보건',
  matchKeywords: ['간호', '보건', '임상', '환자', 'osce', '의료', '병원', '간호학'],
  courseNatureTemplate:
    '환자의 생명과 안전을 다루는 실습 중심 과목으로, 이론 지식이 반드시 표준화된 술기 수행으로 연결되어야 한다. 오류가 곧 환자 위해로 이어질 수 있어 정확성과 절차 준수가 핵심 평가 기준이 된다.',
  studentCharacteristics:
    '임상 실습에 대한 기대와 긴장이 공존하며, 술기 하나하나를 정확한 순서로 암기·재현해야 한다는 부담이 크다. 이론 수업보다 직접 시연·반복 연습에서 학습 효과가 크게 나타난다.',
  prerequisitesPool: [
    '해부생리학 기초 지식',
    '기본 의학용어 이해',
    '감염관리 표준주의 개념',
    '활력징후의 정상 범위에 대한 사전 이해',
  ],
  coreConcepts: [
    '간호과정(사정-진단-계획-수행-평가)',
    '표준주의 및 감염관리',
    '무균술(내과적/외과적)',
    '환자안전 원칙',
    '활력징후 사정',
    '의사소통 및 공감적 케어',
    'OSCE 술기 표준 절차',
    '기록 및 인수인계(SBAR)',
  ],
  difficultiesPool: [
    '술기 순서를 정확히 암기하고 손으로 재현하는 데 시간이 오래 걸림',
    '이론(생리학적 근거)과 실습 동작을 연결하지 못하고 절차만 외우는 경향',
    '멸균/오염 구분처럼 눈에 보이지 않는 개념을 체득하기 어려움',
    '환자 응대 시 긴장으로 의사소통 절차를 누락하기 쉬움',
  ],
  aiApplicability:
    'AI는 술기 순서 요약표, 정상/비정상 판별 기준표, 흔한 오류 체크리스트 생성 등 "정리·요약" 보조 도구로 유효하다. 다만 실제 술기 수행 판정과 환자 관련 의사결정은 반드시 교수자·임상 지도자의 직접 검증을 거쳐야 한다.',
  instructorJudgmentPool: [
    '실습 그룹별 숙련도 편차에 따른 개별 지도 필요 여부',
    'AI가 생성한 정상수치 기준표의 최신 임상 가이드라인 부합 여부 검토',
    '환자 시나리오의 임상적 타당성 최종 확인',
  ],
  weekTopics: [
    {
      title: '활력징후 측정(체온·맥박·호흡)',
      coreConcepts: '체온 조절기전, 맥박 측정 부위, 호흡 사정 기준',
      teachingHint: '측정 원리 강의 및 표준 절차 시범',
      studentHint: '2인 1조 체온·맥박·호흡 측정 실습 및 상호 점검',
      practiceHint: '정상/비정상 판별 실습',
      aiUsageHint: 'AI로 연령별 정상 활력징후 범위 요약표 생성(교수자 검토 후 배포)',
    },
    {
      title: '혈압 측정 및 종합 사정',
      coreConcepts: '혈압 측정 원리, 코로트코프음, 활력징후 종합 기록',
      teachingHint: '혈압계 사용법 시범 및 흔한 오류 사례 강의',
      studentHint: '2인 1조 혈압 측정 실습 및 상호 평가',
      practiceHint: '측정값 기록 및 판별 실습',
      aiUsageHint: 'AI로 흔한 측정 오류 체크리스트 생성',
    },
    {
      title: '감염관리의 기본 원칙',
      coreConcepts: '감염 사슬, 표준주의(Standard Precaution), 손위생',
      teachingHint: '감염관리 이론 강의 및 손위생 6단계 시범',
      studentHint: '손위생 6단계 실습 및 형광물질 검증',
      practiceHint: '감염 사슬 6요소 분석 실습',
      aiUsageHint: 'AI로 감염 사슬 6요소 요약카드 생성',
    },
    {
      title: '무균술(내과적 무균법)',
      coreConcepts: '내과적 무균법, 격리술, 오염과 청결 구분',
      teachingHint: '내과적 무균법 원리 강의 및 시범',
      studentHint: '무균 장갑 착용 실습',
      practiceHint: '절차 순서도 작성 실습',
      aiUsageHint: 'AI로 무균술 절차 순서 체크리스트 생성',
    },
    {
      title: '무균술(외과적 무균법)',
      coreConcepts: '외과적 무균법, 멸균 영역, 오염 원칙',
      teachingHint: '외과적 무균법 원리 강의 및 시범',
      studentHint: '멸균 장갑 착용 및 멸균 영역 준비 실습',
      practiceHint: '내과적·외과적 무균법 비교 실습',
      aiUsageHint: 'AI로 내과적·외과적 무균법 비교표 생성',
    },
    {
      title: '개인보호구(PPE) 착용과 탈의',
      coreConcepts: '개인보호구 종류, 착용·탈의 순서, 교차오염 예방',
      teachingHint: 'PPE 착용·탈의 순서 강의 및 시범',
      studentHint: 'PPE 착용·탈의 실습 및 상호 점검',
      practiceHint: '착용·탈의 순서 카드 제작 실습',
      aiUsageHint: 'AI로 PPE 착용·탈의 순서 카드 생성',
    },
    {
      title: '체위변경과 이동 보조',
      coreConcepts: '신체역학 원리, 체위변경 종류, 낙상 예방',
      teachingHint: '신체역학 원리 강의 및 체위변경 시범',
      studentHint: '2인 1조 체위변경 및 이동 보조 실습',
      practiceHint: '낙상 위험 요인 사정 실습',
      aiUsageHint: 'AI로 체위별 적응증·금기 요약표 생성',
    },
    {
      title: '투약의 기본 원칙(경구·비경구)',
      coreConcepts: '투약 5 Right, 경구·비경구 투약 절차, 투약 오류 예방',
      teachingHint: '투약 원칙 강의 및 절차 시범',
      studentHint: '모형을 이용한 투약 절차 실습',
      practiceHint: '투약 오류 사례 분석 실습',
      aiUsageHint: 'AI로 투약 5 Right 체크리스트 생성',
    },
    {
      title: '상처 관리 및 드레싱',
      coreConcepts: '상처 치유 단계, 드레싱 종류, 무균 드레싱 절차',
      teachingHint: '상처 치유 생리 및 드레싱 원리 강의',
      studentHint: '무균 드레싱 교체 실습',
      practiceHint: '드레싱 재료 선택 실습',
      aiUsageHint: 'AI로 상처 유형별 드레싱 선택 가이드 생성',
    },
    {
      title: '배뇨·배변 간호',
      coreConcepts: '배설 사정, 유치도뇨 원리, 변비/실금 간호',
      teachingHint: '배설 간호 이론 강의 및 절차 시범',
      studentHint: '유치도뇨 모형 실습',
      practiceHint: '배설 기록지 작성 실습',
      aiUsageHint: 'AI로 배설 사정 기록 양식 생성',
    },
    {
      title: '환자안전과 의사소통(SBAR)',
      coreConcepts: 'SBAR 인수인계, 근접오류 보고, 환자 확인 절차',
      teachingHint: 'SBAR 기법 강의 및 사례 시연',
      studentHint: '역할극으로 SBAR 인수인계 실습',
      practiceHint: '인수인계 시나리오 작성 실습',
      aiUsageHint: 'AI로 SBAR 인수인계 스크립트 초안 생성 후 교수자 검토',
    },
  ],
  aiTools: [
    {
      name: 'AI 요약 도우미(범용 LLM 챗봇)',
      purpose: '술기 절차·정상수치 기준을 표 형태로 요약',
      instructorUse: '생성된 요약표의 임상적 정확성을 검토한 뒤 배포 자료로 활용',
      studentUse: '실습 전 예습용 절차 요약표로 참고(최종 확인은 교재·지침 기준)',
      caution: '환자 관련 실제 데이터·개인정보는 절대 입력하지 않는다',
      alternative: '학교 도서관 임상 데이터베이스, 표준 간호 술기 지침서',
    },
    {
      name: 'AI 체크리스트 생성기',
      purpose: '술기 단계별 자가점검 체크리스트 생성',
      instructorUse: '체크리스트 항목을 실습 평가 기준과 대조 검토',
      studentUse: '실습 전후 자가점검용으로 활용',
      caution: '체크리스트가 최신 임상 지침을 반영하는지 매 학기 확인 필요',
      alternative: '병원 표준 술기 매뉴얼',
    },
  ],
  practiceNamesPool: [
    '활력징후 측정 실습',
    '무균술 수행 실습',
    'PPE 착용·탈의 실습',
    '투약 절차 시뮬레이션',
    '상처 드레싱 실습',
    'SBAR 인수인계 역할극',
  ],
  caseScenarioPool: [
    '수술 후 회복실에서 활력징후가 불안정한 환자 사례',
    '감염관리 지침을 지키지 않아 발생한 교차오염 사례',
    '투약 오류가 발생할 뻔했던 아차사고(near-miss) 사례',
    '낙상 위험이 높은 고령 환자의 이동 보조 사례',
  ],
  projectThemePool: [
    '병동 감염관리 개선 캠페인 기획',
    '환자안전 사고 예방을 위한 체크리스트 개발',
    '신입 간호학생을 위한 술기 가이드북 제작',
  ],
  ethicsNotesPool: [
    '실습 시나리오에는 실제 환자의 개인정보를 절대 포함하지 않는다',
    'AI가 생성한 임상 정보는 반드시 최신 지침과 대조 검증한다',
  ],
  vocabulary: ['환자안전', '술기', '표준주의', '임상현장', '간호과정', 'OSCE'],
}
